this here is the data pipeline for turning the data into tuples!

In [15]:
#load packages
import numpy as np
import mne
import pandas as pd
from scipy.signal import coherence
from scipy.signal import welch

In [ ]:
# loading data from:https://physionet.org/content/eegmat/1.0.0/
# dataset has a low-pass filter at 30Hz so gamma (30+Hz) has minimal signal
# _1 files = baseline EEG, _2 files = EEG during mental arithmetic task
# load files in subject order, trim each one before combining
files = [
    ('Subject00_1.edf', 0, 'baseline'),
    ('Subject00_2.edf', 0, 'task'),
    ('Subject01_1.edf', 1, 'baseline'),
    ('Subject01_2.edf', 1, 'task'),
    ('Subject02_1.edf', 2, 'baseline'),
    ('Subject02_2.edf', 2, 'task'),
    ('Subject03_1.edf', 3, 'baseline'),
    ('Subject03_2.edf', 3, 'task'),
    ('Subject04_1.edf', 4, 'baseline'),
    ('Subject04_2.edf', 4, 'task'),
    ('Subject05_1.edf', 5, 'baseline'),
    ('Subject05_2.edf', 5, 'task'),
]
trimmed = []

for f, subject_id, session in files:
    raw = mne.io.read_raw_edf(f, preload=True, encoding='latin1')
    temp = raw.to_data_frame()
    temp = temp.drop(columns=['ECG ECG'])
    
    # trim flat padding off the end of each file
    eeg_data = temp[[col for col in temp.columns if col.startswith('EEG')]]
    changing = (eeg_data.diff() != 0).any(axis=1)
    last_valid = changing[::-1].idxmax()
    temp = temp.iloc[:last_valid + 1]
    
    # tag each row with subject and session so teammates know the source
    temp['subject_id'] = subject_id
    temp['session'] = session
    
    print(f'{f}: {len(temp)} valid rows')
    trimmed.append(temp)

df = pd.concat(trimmed, ignore_index=True)
df

Extracting EDF parameters from Subject00_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...

Subject00_1.edf: 90546 valid rows
Extracting EDF parameters from Subject00_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject00_2.edf: 30515 valid rows
Extracting EDF parameters from Subject01_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Subject01_1.edf: 90546 valid rows
Extracting EDF parameters from Subject01_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject01_2.edf: 30515 valid rows
Extracting EDF parameters from Subject02_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Subject02_1.edf: 90546 valid rows
Extracting EDF parameters from Subject02_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject02_2.edf: 30515 valid rows
Extracting EDF parameters from Subject03_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Subject03_1.edf: 90546 valid rows
Extracting EDF parameters from Subject03_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject03_2.edf: 30515 valid rows
Extracting EDF parameters from Subject04_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 84999  =      0.000 ...   169.998 secs...
Subject04_1.edf: 84547 valid rows
Extracting EDF parameters from Subject04_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject04_2.edf: 30515 valid rows
Extracting EDF parameters from Subject05_1.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 90999  =      0.000 ...   181.998 secs...
Subject05_1.edf: 90546 valid rows
Extracting EDF parameters from Subject05_2.edf...
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 30999  =      0.000 ...    61.998 secs...
Subject05_2.edf: 30515 valid rows
Total rows: 720367

,time,EEG Fp1,EEG Fp2,EEG F3,EEG F4,EEG F7,EEG F8,EEG T3,EEG T4,EEG C3,...,EEG P3,EEG P4,EEG O1,EEG O2,EEG Fz,EEG Cz,EEG Pz,EEG A2-A1,subject_id,session
0,0.000,-3.647938,-3.581866,-4.081247,-0.237508,-3.460168,-1.021940,-1.619108,4.479832,-1.957309,...,1.076818,7.086144,4.313824,10.168745,-0.227751,0.358397,2.822136,1.291542,0,baseline
1,0.002,-4.236482,-4.279388,-4.766219,-0.617699,-3.709403,-1.308793,-0.877716,5.607640,-1.426855,...,2.962960,9.159618,6.237584,12.274858,-0.602733,4.160351,5.311727,0.973219,0,baseline
2,0.004,-4.954218,-5.020849,-5.783455,-1.193804,-3.903253,-1.523457,0.171455,7.056246,-0.864033,...,5.318983,11.767794,8.766892,14.835672,-1.163293,8.861065,8.367278,0.579025,0,baseline
3,0.006,-5.703854,-5.656125,-7.079280,-1.928968,-4.019562,-1.548153,1.453587,8.670264,-0.369542,...,7.870239,14.621829,11.722487,17.598852,-1.882648,13.699181,11.597705,0.182633,0,baseline
4,0.008,-6.370552,-6.046078,-8.518234,-2.747541,-4.076794,-1.278398,2.842846,10.249195,-0.027893,...,10.264316,17.350356,14.857342,20.304570,-2.682355,17.717742,14.534023,-0.119747,0,baseline
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720362,61.020,-6.225414,11.253639,-1.699319,-7.326075,-1.923019,-3.876462,-5.228226,-17.340635,-2.889137,...,2.558638,14.437941,13.393328,9.322056,-3.436279,-1.041213,9.576340,1.239656,5,task
720363,61.022,-6.225414,11.253639,-1.699319,-7.326075,-1.923019,-3.876462,-5.228226,-17.340635,-2.889137,...,2.558638,14.437941,13.393328,9.322056,-3.436279,-1.041213,9.576340,1.239656,5,task
720364,61.024,-6.225414,11.253639,-1.699319,-7.326075,-1.923019,-3.876462,-5.228226,-17.340635,-2.889137,...,2.558638,14.437941,13.393328,9.322056,-3.436279,-1.041213,9.576340,1.239656,5,task
720365,61.026,-6.225414,11.253639,-1.699319,-7.326075,-1.923019,-3.876462,-5.228226,-17.340635,-2.889137,...,2.558638,14.437941,13.393328,9.322056,-3.436279,-1.041213,9.576340,1.239656,5,task
720366,61.028,-0.001432,0.001503,-0.000385,-0.000107,-0.001350,-0.000243,-0.000679,-0.001545,-0.001163,...,0.000490,0.001813,0.001064,0.000759,-0.001229,-0.000930,0.000458,0.000568,5,task

In [ ]:
#make full second sized windows for proper frequency resolution
fs=500
window_size=500
n_windows=len(df)//window_size

#get all channels as long as they are eeg channels
channels = []
for col in df.columns:
    if col.startswith('EEG'):
        channels.append(col)

print(f"n_windows: {n_windows}")
print(f"expected coherence rows: {n_windows*190}")
print(f"channels: {channels}")

n_windows: 1440
expected coherence rows: 273600
channels: ['EEG Fp1', 'EEG Fp2', 'EEG F3', 'EEG F4', 'EEG F7', 'EEG F8', 'EEG T3', 'EEG T4', 'EEG C3', 'EEG C4', 'EEG T5', 'EEG T6', 'EEG P3', 'EEG P4', 'EEG O1', 'EEG O2', 'EEG Fz', 'EEG Cz', 'EEG Pz', 'EEG A2-A1']

In [ ]:
# band definitions for coherence
# delta, theta, alpha, beta have strong signal
BANDS = {
    'delta':(0.5,4),
    'theta':(4,8),
    'alpha':(8,13),
    'beta':(13,30),
    'gamma':(30,45)
}

# window loop to find band-specific coherence of pairs per window
# no pre-filtering needed: scipy.signal.coherence already returns per-frequency values
# we just mask the output by band range (same technique as band power)
output_list = []
for w in range(n_windows):
    print(f"window #: {w} of {n_windows}")
    start=w*window_size
    end=start+window_size
    window_data=df.iloc[start:end]
    mid = start + window_size // 2
    subj = df.iloc[mid]['subject_id']
    sess = df.iloc[mid]['session']

    for i in range(len(channels)):
        for j in range(i+1, len(channels)):
            channel1 = channels[i]
            channel2 = channels[j]
            freqs, coh = coherence(window_data[channel1].values, window_data[channel2].values, fs=500.0, nperseg=256)
            row = {'epoch_id': w, 'subject_id': subj, 'session': sess, 'channel_i': channel1, 'channel_j': channel2}
            for band, (lo, hi) in BANDS.items():
                mask = (freqs >= lo) & (freqs < hi)
                row[band + '_coherence'] = coh[mask].mean()
            output_list.append(row)

output_df = pd.DataFrame(output_list)

# clean up bad values from dying signal at file boundaries
output_df = output_df.dropna()
output_df = output_df[output_df['delta_coherence'] < 1.0]
output_df = output_df[output_df['theta_coherence'] < 1.0]
output_df = output_df[output_df['alpha_coherence'] < 1.0]
output_df = output_df[output_df['beta_coherence'] < 1.0]
print(f"Total coherence rows: {len(output_df)}")
output_df

window #: 0 of 1440
window #: 1 of 1440
window #: 2 of 1440
window #: 3 of 1440
window #: 4 of 1440
window #: 5 of 1440
window #: 6 of 1440
window #: 7 of 1440
window #: 8 of 1440
window #: 9 of 1440
window #: 10 of 1440
window #: 11 of 1440
window #: 12 of 1440
window #: 13 of 1440
window #: 14 of 1440
window #: 15 of 1440
window #: 16 of 1440
window #: 17 of 1440
window #: 18 of 1440
window #: 19 of 1440
window #: 20 of 1440
window #: 21 of 1440
window #: 22 of 1440
window #: 23 of 1440
window #: 24 of 1440
window #: 25 of 1440
window #: 26 of 1440
window #: 27 of 1440
window #: 28 of 1440
window #: 29 of 1440
window #: 30 of 1440
window #: 31 of 1440
window #: 32 of 1440
window #: 33 of 1440
window #: 34 of 1440
window #: 35 of 1440
window #: 36 of 1440
window #: 37 of 1440
window #: 38 of 1440
window #: 39 of 1440
window #: 40 of 1440
window #: 41 of 1440
window #: 42 of 1440
window #: 43 of 1440
window #: 44 of 1440
window #: 45 of 1440
window #: 46 of 1440
window #: 47 of 1440
window #: 48 of 1440
window #: 49 of 1440
window #: 50 of 1440
window #: 51 of 1440
window #: 52 of 1440
window #: 53 of 1440
window #: 54 of 1440
window #: 55 of 1440
window #: 56 of 1440
window #: 57 of 1440
window #: 58 of 1440
window #: 59 of 1440
window #: 60 of 1440
window #: 61 of 1440
window #: 62 of 1440
window #: 63 of 1440
window #: 64 of 1440
window #: 65 of 1440
window #: 66 of 1440
window #: 67 of 1440
window #: 68 of 1440
window #: 69 of 1440
window #: 70 of 1440
window #: 71 of 1440
window #: 72 of 1440
window #: 73 of 1440
window #: 74 of 1440
window #: 75 of 1440
window #: 76 of 1440
window #: 77 of 1440
window #: 78 of 1440
window #: 79 of 1440
window #: 80 of 1440
window #: 81 of 1440
window #: 82 of 1440
window #: 83 of 1440
window #: 84 of 1440
window #: 85 of 1440
window #: 86 of 1440
window #: 87 of 1440
window #: 88 of 1440
window #: 89 of 1440
window #: 90 of 1440
window #: 91 of 1440
window #: 92 of 1440
window #: 93 of 1440
window #: 94 of 1440
window #: 95 of 1440
window #: 96 of 1440
window #: 97 of 1440
window #: 98 of 1440
window #: 99 of 1440
window #: 100 of 1440
window #: 101 of 1440
window #: 102 of 1440
window #: 103 of 1440
window #: 104 of 1440
window #: 105 of 1440
window #: 106 of 1440
window #: 107 of 1440
window #: 108 of 1440
window #: 109 of 1440
window #: 110 of 1440
window #: 111 of 1440
window #: 112 of 1440
window #: 113 of 1440
window #: 114 of 1440
window #: 115 of 1440
window #: 116 of 1440
window #: 117 of 1440
window #: 118 of 1440
window #: 119 of 1440
window #: 120 of 1440
window #: 121 of 1440
window #: 122 of 1440
window #: 123 of 1440
window #: 124 of 1440
window #: 125 of 1440
window #: 126 of 1440
window #: 127 of 1440
window #: 128 of 1440
window #: 129 of 1440
window #: 130 of 1440
window #: 131 of 1440
window #: 132 of 1440
window #: 133 of 1440
window #: 134 of 1440
window #: 135 of 1440
window #: 136 of 1440
window #: 137 of 1440
window #: 138 of 1440
window #: 139 of 1440
window #: 140 of 1440
window #: 141 of 1440
window #: 142 of 1440
window #: 143 of 1440
window #: 144 of 1440
window #: 145 of 1440
window #: 146 of 1440
window #: 147 of 1440
window #: 148 of 1440
window #: 149 of 1440
window #: 150 of 1440
window #: 151 of 1440
window #: 152 of 1440
window #: 153 of 1440
window #: 154 of 1440
window #: 155 of 1440
window #: 156 of 1440
window #: 157 of 1440
window #: 158 of 1440
window #: 159 of 1440
window #: 160 of 1440
window #: 161 of 1440
window #: 162 of 1440
window #: 163 of 1440
window #: 164 of 1440
window #: 165 of 1440
window #: 166 of 1440
window #: 167 of 1440
window #: 168 of 1440
window #: 169 of 1440
window #: 170 of 1440
window #: 171 of 1440
window #: 172 of 1440
window #: 173 of 1440
window #: 174 of 1440
window #: 175 of 1440
window #: 176 of 1440
window #: 177 of 1440
window #: 178 of 1440
window #: 179 of 1440
window #: 180 of 1440
window #: 181 of 1440
window #: 182 of 1440
window #: 183 of 1440
window #: 184 of 1440
window #: 185 of 1440
window #: 186 of 1440
window #: 187 of 1440
window #: 188 of 1440
window #: 189 of 1440
window #: 190 of 1440
window #: 191 of 1440
window #: 192 of 1440
window #: 193 of 1440
window #: 194 of 1440
window #: 195 of 1440
window #: 196 of 1440
window #: 197 of 1440
window #: 198 of 1440
window #: 199 of 1440
window #: 200 of 1440
window #: 201 of 1440
window #: 202 of 1440
window #: 203 of 1440
window #: 204 of 1440
window #: 205 of 1440
window #: 206 of 1440
window #: 207 of 1440
window #: 208 of 1440
window #: 209 of 1440
window #: 210 of 1440
window #: 211 of 1440
window #: 212 of 1440
window #: 213 of 1440
window #: 214 of 1440
window #: 215 of 1440
window #: 216 of 1440
window #: 217 of 1440
window #: 218 of 1440
window #: 219 of 1440
window #: 220 of 1440
window #: 221 of 1440
window #: 222 of 1440
window #: 223 of 1440
window #: 224 of 1440
window #: 225 of 1440
window #: 226 of 1440
window #: 227 of 1440
window #: 228 of 1440
window #: 229 of 1440
window #: 230 of 1440
window #: 231 of 1440
window #: 232 of 1440
window #: 233 of 1440
window #: 234 of 1440
window #: 235 of 1440
window #: 236 of 1440
window #: 237 of 1440
window #: 238 of 1440
window #: 239 of 1440
window #: 240 of 1440
window #: 241 of 1440
window #: 242 of 1440
window #: 243 of 1440
window #: 244 of 1440
window #: 245 of 1440
window #: 246 of 1440
window #: 247 of 1440
window #: 248 of 1440
window #: 249 of 1440
window #: 250 of 1440
window #: 251 of 1440
window #: 252 of 1440
window #: 253 of 1440
window #: 254 of 1440
window #: 255 of 1440
window #: 256 of 1440
window #: 257 of 1440
window #: 258 of 1440
window #: 259 of 1440
window #: 260 of 1440
window #: 261 of 1440
window #: 262 of 1440
window #: 263 of 1440
window #: 264 of 1440
window #: 265 of 1440
window #: 266 of 1440
window #: 267 of 1440
window #: 268 of 1440
window #: 269 of 1440
window #: 270 of 1440
window #: 271 of 1440
window #: 272 of 1440
window #: 273 of 1440
window #: 274 of 1440
window #: 275 of 1440
window #: 276 of 1440
window #: 277 of 1440
window #: 278 of 1440
window #: 279 of 1440
window #: 280 of 1440
window #: 281 of 1440
window #: 282 of 1440
window #: 283 of 1440
window #: 284 of 1440
window #: 285 of 1440
window #: 286 of 1440
window #: 287 of 1440
window #: 288 of 1440
window #: 289 of 1440
window #: 290 of 1440
window #: 291 of 1440
window #: 292 of 1440
window #: 293 of 1440
window #: 294 of 1440
window #: 295 of 1440
window #: 296 of 1440
window #: 297 of 1440
window #: 298 of 1440
window #: 299 of 1440
window #: 300 of 1440
window #: 301 of 1440
window #: 302 of 1440
window #: 303 of 1440
window #: 304 of 1440
window #: 305 of 1440
window #: 306 of 1440
window #: 307 of 1440
window #: 308 of 1440
window #: 309 of 1440
window #: 310 of 1440
window #: 311 of 1440
window #: 312 of 1440
window #: 313 of 1440
window #: 314 of 1440
window #: 315 of 1440
window #: 316 of 1440
window #: 317 of 1440
window #: 318 of 1440
window #: 319 of 1440
window #: 320 of 1440
window #: 321 of 1440
window #: 322 of 1440
window #: 323 of 1440
window #: 324 of 1440
window #: 325 of 1440
window #: 326 of 1440
window #: 327 of 1440
window #: 328 of 1440
window #: 329 of 1440
window #: 330 of 1440
window #: 331 of 1440
window #: 332 of 1440
window #: 333 of 1440
window #: 334 of 1440
window #: 335 of 1440
window #: 336 of 1440
window #: 337 of 1440
window #: 338 of 1440
window #: 339 of 1440
window #: 340 of 1440
window #: 341 of 1440
window #: 342 of 1440
window #: 343 of 1440
window #: 344 of 1440
window #: 345 of 1440
window #: 346 of 1440
window #: 347 of 1440
window #: 348 of 1440
window #: 349 of 1440
window #: 350 of 1440
window #: 351 of 1440
window #: 352 of 1440
window #: 353 of 1440
window #: 354 of 1440
window #: 355 of 1440
window #: 356 of 1440
window #: 357 of 1440
window #: 358 of 1440
window #: 359 of 1440
window #: 360 of 1440
window #: 361 of 1440
window #: 362 of 1440
window #: 363 of 1440
window #: 364 of 1440
window #: 365 of 1440
window #: 366 of 1440
window #: 367 of 1440
window #: 368 of 1440
window #: 369 of 1440
window #: 370 of 1440
window #: 371 of 1440
window #: 372 of 1440
window #: 373 of 1440
window #: 374 of 1440
window #: 375 of 1440
window #: 376 of 1440
window #: 377 of 1440
window #: 378 of 1440
window #: 379 of 1440
window #: 380 of 1440
window #: 381 of 1440
window #: 382 of 1440
window #: 383 of 1440
window #: 384 of 1440
window #: 385 of 1440
window #: 386 of 1440
window #: 387 of 1440
window #: 388 of 1440
window #: 389 of 1440
window #: 390 of 1440
window #: 391 of 1440
window #: 392 of 1440
window #: 393 of 1440
window #: 394 of 1440
window #: 395 of 1440
window #: 396 of 1440
window #: 397 of 1440
window #: 398 of 1440
window #: 399 of 1440
window #: 400 of 1440
window #: 401 of 1440
window #: 402 of 1440
window #: 403 of 1440
window #: 404 of 1440
window #: 405 of 1440
window #: 406 of 1440
window #: 407 of 1440
window #: 408 of 1440
window #: 409 of 1440
window #: 410 of 1440
window #: 411 of 1440
window #: 412 of 1440
window #: 413 of 1440
window #: 414 of 1440
window #: 415 of 1440
window #: 416 of 1440
window #: 417 of 1440
window #: 418 of 1440
window #: 419 of 1440
window #: 420 of 1440
window #: 421 of 1440
window #: 422 of 1440
window #: 423 of 1440
window #: 424 of 1440
window #: 425 of 1440
window #: 426 of 1440
window #: 427 of 1440
window #: 428 of 1440
window #: 429 of 1440
window #: 430 of 1440
window #: 431 of 1440
window #: 432 of 1440
window #: 433 of 1440
window #: 434 of 1440
window #: 435 of 1440
window #: 436 of 1440
window #: 437 of 1440
window #: 438 of 1440
window #: 439 of 1440
window #: 440 of 1440
window #: 441 of 1440
window #: 442 of 1440
window #: 443 of 1440
window #: 444 of 1440
window #: 445 of 1440
window #: 446 of 1440
window #: 447 of 1440
window #: 448 of 1440
window #: 449 of 1440
window #: 450 of 1440
window #: 451 of 1440
window #: 452 of 1440
window #: 453 of 1440
window #: 454 of 1440
window #: 455 of 1440
window #: 456 of 1440
window #: 457 of 1440
window #: 458 of 1440
window #: 459 of 1440
window #: 460 of 1440
window #: 461 of 1440
window #: 462 of 1440
window #: 463 of 1440
window #: 464 of 1440
window #: 465 of 1440
window #: 466 of 1440
window #: 467 of 1440
window #: 468 of 1440
window #: 469 of 1440
window #: 470 of 1440
window #: 471 of 1440
window #: 472 of 1440
window #: 473 of 1440
window #: 474 of 1440
window #: 475 of 1440
window #: 476 of 1440
window #: 477 of 1440
window #: 478 of 1440
window #: 479 of 1440
window #: 480 of 1440
window #: 481 of 1440
window #: 482 of 1440
window #: 483 of 1440
window #: 484 of 1440
window #: 485 of 1440
window #: 486 of 1440
window #: 487 of 1440
window #: 488 of 1440
window #: 489 of 1440
window #: 490 of 1440
window #: 491 of 1440
window #: 492 of 1440
window #: 493 of 1440
window #: 494 of 1440
window #: 495 of 1440
window #: 496 of 1440
window #: 497 of 1440
window #: 498 of 1440
window #: 499 of 1440
window #: 500 of 1440
window #: 501 of 1440
window #: 502 of 1440
window #: 503 of 1440
window #: 504 of 1440
window #: 505 of 1440
window #: 506 of 1440
window #: 507 of 1440
window #: 508 of 1440
window #: 509 of 1440
window #: 510 of 1440
window #: 511 of 1440
window #: 512 of 1440
window #: 513 of 1440
window #: 514 of 1440
window #: 515 of 1440
window #: 516 of 1440
window #: 517 of 1440
window #: 518 of 1440
window #: 519 of 1440
window #: 520 of 1440
window #: 521 of 1440
window #: 522 of 1440
window #: 523 of 1440
window #: 524 of 1440
window #: 525 of 1440
window #: 526 of 1440
window #: 527 of 1440
window #: 528 of 1440
window #: 529 of 1440
window #: 530 of 1440
window #: 531 of 1440
window #: 532 of 1440
window #: 533 of 1440
window #: 534 of 1440
window #: 535 of 1440
window #: 536 of 1440
window #: 537 of 1440
window #: 538 of 1440
window #: 539 of 1440
window #: 540 of 1440
window #: 541 of 1440
window #: 542 of 1440
window #: 543 of 1440
window #: 544 of 1440
window #: 545 of 1440
window #: 546 of 1440
window #: 547 of 1440
window #: 548 of 1440
window #: 549 of 1440
window #: 550 of 1440
window #: 551 of 1440
window #: 552 of 1440
window #: 553 of 1440
window #: 554 of 1440
window #: 555 of 1440
window #: 556 of 1440
window #: 557 of 1440
window #: 558 of 1440
window #: 559 of 1440
window #: 560 of 1440
window #: 561 of 1440
window #: 562 of 1440
window #: 563 of 1440
window #: 564 of 1440
window #: 565 of 1440
window #: 566 of 1440
window #: 567 of 1440
window #: 568 of 1440
window #: 569 of 1440
window #: 570 of 1440
window #: 571 of 1440
window #: 572 of 1440
window #: 573 of 1440
window #: 574 of 1440
window #: 575 of 1440
window #: 576 of 1440
window #: 577 of 1440
window #: 578 of 1440
window #: 579 of 1440
window #: 580 of 1440
window #: 581 of 1440
window #: 582 of 1440
window #: 583 of 1440
window #: 584 of 1440
window #: 585 of 1440
window #: 586 of 1440
window #: 587 of 1440
window #: 588 of 1440
window #: 589 of 1440
window #: 590 of 1440
window #: 591 of 1440
window #: 592 of 1440
window #: 593 of 1440
window #: 594 of 1440
window #: 595 of 1440
window #: 596 of 1440
window #: 597 of 1440
window #: 598 of 1440
window #: 599 of 1440
window #: 600 of 1440
window #: 601 of 1440
window #: 602 of 1440
window #: 603 of 1440
window #: 604 of 1440
window #: 605 of 1440
window #: 606 of 1440
window #: 607 of 1440
window #: 608 of 1440
window #: 609 of 1440
window #: 610 of 1440
window #: 611 of 1440
window #: 612 of 1440
window #: 613 of 1440
window #: 614 of 1440
window #: 615 of 1440
window #: 616 of 1440
window #: 617 of 1440
window #: 618 of 1440
window #: 619 of 1440
window #: 620 of 1440
window #: 621 of 1440
window #: 622 of 1440
window #: 623 of 1440
window #: 624 of 1440
window #: 625 of 1440
window #: 626 of 1440
window #: 627 of 1440
window #: 628 of 1440
window #: 629 of 1440
window #: 630 of 1440
window #: 631 of 1440
window #: 632 of 1440
window #: 633 of 1440
window #: 634 of 1440
window #: 635 of 1440
window #: 636 of 1440
window #: 637 of 1440
window #: 638 of 1440
window #: 639 of 1440
window #: 640 of 1440
window #: 641 of 1440
window #: 642 of 1440
window #: 643 of 1440
window #: 644 of 1440
window #: 645 of 1440
window #: 646 of 1440
window #: 647 of 1440
window #: 648 of 1440
window #: 649 of 1440
window #: 650 of 1440
window #: 651 of 1440
window #: 652 of 1440
window #: 653 of 1440
window #: 654 of 1440
window #: 655 of 1440
window #: 656 of 1440
window #: 657 of 1440
window #: 658 of 1440
window #: 659 of 1440
window #: 660 of 1440
window #: 661 of 1440
window #: 662 of 1440
window #: 663 of 1440
window #: 664 of 1440
window #: 665 of 1440
window #: 666 of 1440
window #: 667 of 1440
window #: 668 of 1440
window #: 669 of 1440
window #: 670 of 1440
window #: 671 of 1440
window #: 672 of 1440
window #: 673 of 1440
window #: 674 of 1440
window #: 675 of 1440
window #: 676 of 1440
window #: 677 of 1440
window #: 678 of 1440
window #: 679 of 1440
window #: 680 of 1440
window #: 681 of 1440
window #: 682 of 1440
window #: 683 of 1440
window #: 684 of 1440
window #: 685 of 1440
window #: 686 of 1440
window #: 687 of 1440
window #: 688 of 1440
window #: 689 of 1440
window #: 690 of 1440
window #: 691 of 1440
window #: 692 of 1440
window #: 693 of 1440
window #: 694 of 1440
window #: 695 of 1440
window #: 696 of 1440
window #: 697 of 1440
window #: 698 of 1440
window #: 699 of 1440
window #: 700 of 1440
window #: 701 of 1440
window #: 702 of 1440
window #: 703 of 1440
window #: 704 of 1440
window #: 705 of 1440
window #: 706 of 1440
window #: 707 of 1440
window #: 708 of 1440
window #: 709 of 1440
window #: 710 of 1440
window #: 711 of 1440
window #: 712 of 1440
window #: 713 of 1440
window #: 714 of 1440
window #: 715 of 1440
window #: 716 of 1440
window #: 717 of 1440
window #: 718 of 1440
window #: 719 of 1440
window #: 720 of 1440
window #: 721 of 1440
window #: 722 of 1440
window #: 723 of 1440
window #: 724 of 1440
window #: 725 of 1440
window #: 726 of 1440
window #: 727 of 1440
window #: 728 of 1440
window #: 729 of 1440
window #: 730 of 1440
window #: 731 of 1440
window #: 732 of 1440
window #: 733 of 1440
window #: 734 of 1440
window #: 735 of 1440
window #: 736 of 1440
window #: 737 of 1440
window #: 738 of 1440
window #: 739 of 1440
window #: 740 of 1440
window #: 741 of 1440
window #: 742 of 1440
window #: 743 of 1440
window #: 744 of 1440
window #: 745 of 1440
window #: 746 of 1440
window #: 747 of 1440
window #: 748 of 1440
window #: 749 of 1440
window #: 750 of 1440
window #: 751 of 1440
window #: 752 of 1440
window #: 753 of 1440
window #: 754 of 1440
window #: 755 of 1440
window #: 756 of 1440
window #: 757 of 1440
window #: 758 of 1440
window #: 759 of 1440
window #: 760 of 1440
window #: 761 of 1440
window #: 762 of 1440
window #: 763 of 1440
window #: 764 of 1440
window #: 765 of 1440
window #: 766 of 1440
window #: 767 of 1440
window #: 768 of 1440
window #: 769 of 1440
window #: 770 of 1440
window #: 771 of 1440
window #: 772 of 1440
window #: 773 of 1440
window #: 774 of 1440
window #: 775 of 1440
window #: 776 of 1440
window #: 777 of 1440
window #: 778 of 1440
window #: 779 of 1440
window #: 780 of 1440
window #: 781 of 1440
window #: 782 of 1440
window #: 783 of 1440
window #: 784 of 1440
window #: 785 of 1440
window #: 786 of 1440
window #: 787 of 1440
window #: 788 of 1440
window #: 789 of 1440
window #: 790 of 1440
window #: 791 of 1440
window #: 792 of 1440
window #: 793 of 1440
window #: 794 of 1440
window #: 795 of 1440
window #: 796 of 1440
window #: 797 of 1440
window #: 798 of 1440
window #: 799 of 1440
window #: 800 of 1440
window #: 801 of 1440
window #: 802 of 1440
window #: 803 of 1440
window #: 804 of 1440
window #: 805 of 1440
window #: 806 of 1440
window #: 807 of 1440
window #: 808 of 1440
window #: 809 of 1440
window #: 810 of 1440
window #: 811 of 1440
window #: 812 of 1440
window #: 813 of 1440
window #: 814 of 1440
window #: 815 of 1440
window #: 816 of 1440
window #: 817 of 1440
window #: 818 of 1440
window #: 819 of 1440
window #: 820 of 1440
window #: 821 of 1440
window #: 822 of 1440
window #: 823 of 1440
window #: 824 of 1440
window #: 825 of 1440
window #: 826 of 1440
window #: 827 of 1440
window #: 828 of 1440
window #: 829 of 1440
window #: 830 of 1440
window #: 831 of 1440
window #: 832 of 1440
window #: 833 of 1440
window #: 834 of 1440
window #: 835 of 1440
window #: 836 of 1440
window #: 837 of 1440
window #: 838 of 1440
window #: 839 of 1440
window #: 840 of 1440
window #: 841 of 1440
window #: 842 of 1440
window #: 843 of 1440
window #: 844 of 1440
window #: 845 of 1440
window #: 846 of 1440
window #: 847 of 1440
window #: 848 of 1440
window #: 849 of 1440
window #: 850 of 1440
window #: 851 of 1440
window #: 852 of 1440
window #: 853 of 1440
window #: 854 of 1440
window #: 855 of 1440
window #: 856 of 1440
window #: 857 of 1440
window #: 858 of 1440
window #: 859 of 1440
window #: 860 of 1440
window #: 861 of 1440
window #: 862 of 1440
window #: 863 of 1440
window #: 864 of 1440
window #: 865 of 1440
window #: 866 of 1440
window #: 867 of 1440
window #: 868 of 1440
window #: 869 of 1440
window #: 870 of 1440
window #: 871 of 1440
window #: 872 of 1440
window #: 873 of 1440
window #: 874 of 1440
window #: 875 of 1440
window #: 876 of 1440
window #: 877 of 1440
window #: 878 of 1440
window #: 879 of 1440
window #: 880 of 1440
window #: 881 of 1440
window #: 882 of 1440
window #: 883 of 1440
window #: 884 of 1440
window #: 885 of 1440
window #: 886 of 1440
window #: 887 of 1440
window #: 888 of 1440
window #: 889 of 1440
window #: 890 of 1440
window #: 891 of 1440
window #: 892 of 1440
window #: 893 of 1440
window #: 894 of 1440
window #: 895 of 1440
window #: 896 of 1440
window #: 897 of 1440
window #: 898 of 1440
window #: 899 of 1440
window #: 900 of 1440
window #: 901 of 1440
window #: 902 of 1440
window #: 903 of 1440
window #: 904 of 1440
window #: 905 of 1440
window #: 906 of 1440
window #: 907 of 1440
window #: 908 of 1440
window #: 909 of 1440
window #: 910 of 1440
window #: 911 of 1440
window #: 912 of 1440
window #: 913 of 1440

,epoch_id,subject_id,session,channel_i,channel_j,delta_coherence,theta_coherence,alpha_coherence,beta_coherence,gamma_coherence
0,0,0,baseline,EEG Fp1,EEG Fp2,0.971521,0.974620,0.887708,0.810394,0.913461
1,0,0,baseline,EEG Fp1,EEG F3,0.813916,0.949081,0.961968,0.650274,0.666310
2,0,0,baseline,EEG Fp1,EEG F4,0.683999,0.670868,0.800318,0.692328,0.831752
3,0,0,baseline,EEG Fp1,EEG F7,0.905256,0.906756,0.955570,0.527214,0.423744
4,0,0,baseline,EEG Fp1,EEG F8,0.493458,0.710236,0.529307,0.558200,0.828505
...,...,...,...,...,...,...,...,...,...,...
273595,1439,5,task,EEG Fz,EEG Pz,0.778895,0.701681,0.913111,0.594996,0.803256
273596,1439,5,task,EEG Fz,EEG A2-A1,0.791857,0.479635,0.520106,0.349008,0.458079
273597,1439,5,task,EEG Cz,EEG Pz,0.571413,0.765323,0.451040,0.620141,0.822958
273598,1439,5,task,EEG Cz,EEG A2-A1,0.332221,0.664279,0.210600,0.327074,0.494949
273599,1439,5,task,EEG Pz,EEG A2-A1,0.455058,0.841627,0.748819,0.523701,0.537170

In [19]:
output_df.to_csv('TDG_trial_run_data.csv')

In [ ]:
# band power per channel per window
# delta, theta, alpha, beta have strong signal
# gamma has minimal signal (data is low-pass filtered at 30Hz) but included for completeness
BANDS = {
    'delta': (0.5, 4),
    'theta': (4, 8),
    'alpha': (8, 13),
    'beta': (13, 30),
    'gamma': (30, 45)
}

band_list = []
for w in range(n_windows):
    print(f"Processing band power window {w} of {n_windows}")
    start=w*window_size
    end=start+window_size
    window_data=df.iloc[start:end]
    mid = start + window_size // 2
    subj = df.iloc[mid]['subject_id']
    sess = df.iloc[mid]['session']
    
    for channel in channels:
        segment=window_data[channel].values
        freqs, psd=welch(segment, fs=500.0, nperseg=256)
        
        powers = {}
        for band, (lo, hi) in BANDS.items():
            mask = (freqs >= lo) & (freqs < hi)
            powers[band] = np.sum(psd[mask])
        
        total = sum(powers.values())
        for band in powers:
            powers[band] = powers[band] / total
        
        dominant = max(powers, key=powers.get)
        
        row = {
            'epoch_id': w,
            'subject_id': subj,
            'session': sess,
            'channel': channel,
            'delta': powers['delta'],
            'theta': powers['theta'],
            'alpha': powers['alpha'],
            'beta': powers['beta'],
            'gamma': powers['gamma'],
            'dominant_band': dominant
        }
        band_list.append(row)

band_df = pd.DataFrame(band_list)

# clean up bad values from dying signal at file boundaries
band_df = band_df.dropna()
print(f"Total band power rows: {len(band_df)}")
band_df

Processing band power window 0 of 1440
Processing band power window 1 of 1440
Processing band power window 2 of 1440
Processing band power window 3 of 1440
Processing band power window 4 of 1440
Processing band power window 5 of 1440
Processing band power window 6 of 1440
Processing band power window 7 of 1440
Processing band power window 8 of 1440
Processing band power window 9 of 1440
Processing band power window 10 of 1440
Processing band power window 11 of 1440
Processing band power window 12 of 1440
Processing band power window 13 of 1440
Processing band power window 14 of 1440
Processing band power window 15 of 1440
Processing band power window 16 of 1440
Processing band power window 17 of 1440
Processing band power window 18 of 1440
Processing band power window 19 of 1440
Processing band power window 20 of 1440
Processing band power window 21 of 1440
Processing band power window 22 of 1440
Processing band power window 23 of 1440
Processing band power window 24 of 1440
Processing band power window 25 of 1440
Processing band power window 26 of 1440
Processing band power window 27 of 1440
Processing band power window 28 of 1440
Processing band power window 29 of 1440
Processing band power window 30 of 1440
Processing band power window 31 of 1440
Processing band power window 32 of 1440
Processing band power window 33 of 1440
Processing band power window 34 of 1440
Processing band power window 35 of 1440
Processing band power window 36 of 1440
Processing band power window 37 of 1440
Processing band power window 38 of 1440
Processing band power window 39 of 1440
Processing band power window 40 of 1440
Processing band power window 41 of 1440
Processing band power window 42 of 1440
Processing band power window 43 of 1440
Processing band power window 44 of 1440
Processing band power window 45 of 1440
Processing band power window 46 of 1440
Processing band power window 47 of 1440
Processing band power window 48 of 1440
Processing band power window 49 of 1440
Processing band power window 50 of 1440
Processing band power window 51 of 1440
Processing band power window 52 of 1440
Processing band power window 53 of 1440
Processing band power window 54 of 1440
Processing band power window 55 of 1440
Processing band power window 56 of 1440
Processing band power window 57 of 1440
Processing band power window 58 of 1440
Processing band power window 59 of 1440
Processing band power window 60 of 1440
Processing band power window 61 of 1440
Processing band power window 62 of 1440
Processing band power window 63 of 1440
Processing band power window 64 of 1440
Processing band power window 65 of 1440
Processing band power window 66 of 1440
Processing band power window 67 of 1440
Processing band power window 68 of 1440
Processing band power window 69 of 1440
Processing band power window 70 of 1440
Processing band power window 71 of 1440
Processing band power window 72 of 1440
Processing band power window 73 of 1440
Processing band power window 74 of 1440
Processing band power window 75 of 1440
Processing band power window 76 of 1440
Processing band power window 77 of 1440
Processing band power window 78 of 1440
Processing band power window 79 of 1440
Processing band power window 80 of 1440
Processing band power window 81 of 1440
Processing band power window 82 of 1440
Processing band power window 83 of 1440
Processing band power window 84 of 1440
Processing band power window 85 of 1440
Processing band power window 86 of 1440
Processing band power window 87 of 1440
Processing band power window 88 of 1440
Processing band power window 89 of 1440
Processing band power window 90 of 1440
Processing band power window 91 of 1440
Processing band power window 92 of 1440
Processing band power window 93 of 1440
Processing band power window 94 of 1440
Processing band power window 95 of 1440
Processing band power window 96 of 1440
Processing band power window 97 of 1440
Processing band power window 98 of 1440
Processing band power window 99 of 1440
Processing band power window 100 of 1440
Processing band power window 101 of 1440
Processing band power window 102 of 1440
Processing band power window 103 of 1440
Processing band power window 104 of 1440
Processing band power window 105 of 1440
Processing band power window 106 of 1440
Processing band power window 107 of 1440
Processing band power window 108 of 1440
Processing band power window 109 of 1440
Processing band power window 110 of 1440
Processing band power window 111 of 1440
Processing band power window 112 of 1440
Processing band power window 113 of 1440
Processing band power window 114 of 1440
Processing band power window 115 of 1440
Processing band power window 116 of 1440
Processing band power window 117 of 1440
Processing band power window 118 of 1440
Processing band power window 119 of 1440
Processing band power window 120 of 1440
Processing band power window 121 of 1440
Processing band power window 122 of 1440
Processing band power window 123 of 1440
Processing band power window 124 of 1440
Processing band power window 125 of 1440
Processing band power window 126 of 1440
Processing band power window 127 of 1440
Processing band power window 128 of 1440
Processing band power window 129 of 1440
Processing band power window 130 of 1440
Processing band power window 131 of 1440
Processing band power window 132 of 1440
Processing band power window 133 of 1440
Processing band power window 134 of 1440
Processing band power window 135 of 1440
Processing band power window 136 of 1440
Processing band power window 137 of 1440
Processing band power window 138 of 1440
Processing band power window 139 of 1440
Processing band power window 140 of 1440
Processing band power window 141 of 1440
Processing band power window 142 of 1440
Processing band power window 143 of 1440
Processing band power window 144 of 1440
Processing band power window 145 of 1440
Processing band power window 146 of 1440
Processing band power window 147 of 1440
Processing band power window 148 of 1440
Processing band power window 149 of 1440
Processing band power window 150 of 1440
Processing band power window 151 of 1440
Processing band power window 152 of 1440
Processing band power window 153 of 1440
Processing band power window 154 of 1440
Processing band power window 155 of 1440
Processing band power window 156 of 1440
Processing band power window 157 of 1440
Processing band power window 158 of 1440
Processing band power window 159 of 1440
Processing band power window 160 of 1440
Processing band power window 161 of 1440
Processing band power window 162 of 1440
Processing band power window 163 of 1440
Processing band power window 164 of 1440
Processing band power window 165 of 1440
Processing band power window 166 of 1440
Processing band power window 167 of 1440
Processing band power window 168 of 1440
Processing band power window 169 of 1440
Processing band power window 170 of 1440
Processing band power window 171 of 1440
Processing band power window 172 of 1440
Processing band power window 173 of 1440
Processing band power window 174 of 1440
Processing band power window 175 of 1440
Processing band power window 176 of 1440
Processing band power window 177 of 1440
Processing band power window 178 of 1440
Processing band power window 179 of 1440
Processing band power window 180 of 1440
Processing band power window 181 of 1440
Processing band power window 182 of 1440
Processing band power window 183 of 1440
Processing band power window 184 of 1440
Processing band power window 185 of 1440
Processing band power window 186 of 1440
Processing band power window 187 of 1440
Processing band power window 188 of 1440
Processing band power window 189 of 1440
Processing band power window 190 of 1440
Processing band power window 191 of 1440
Processing band power window 192 of 1440
Processing band power window 193 of 1440
Processing band power window 194 of 1440
Processing band power window 195 of 1440
Processing band power window 196 of 1440
Processing band power window 197 of 1440
Processing band power window 198 of 1440
Processing band power window 199 of 1440
Processing band power window 200 of 1440
Processing band power window 201 of 1440
Processing band power window 202 of 1440
Processing band power window 203 of 1440
Processing band power window 204 of 1440
Processing band power window 205 of 1440
Processing band power window 206 of 1440
Processing band power window 207 of 1440
Processing band power window 208 of 1440
Processing band power window 209 of 1440
Processing band power window 210 of 1440
Processing band power window 211 of 1440
Processing band power window 212 of 1440
Processing band power window 213 of 1440
Processing band power window 214 of 1440
Processing band power window 215 of 1440
Processing band power window 216 of 1440
Processing band power window 217 of 1440
Processing band power window 218 of 1440
Processing band power window 219 of 1440
Processing band power window 220 of 1440
Processing band power window 221 of 1440
Processing band power window 222 of 1440
Processing band power window 223 of 1440
Processing band power window 224 of 1440
Processing band power window 225 of 1440
Processing band power window 226 of 1440
Processing band power window 227 of 1440
Processing band power window 228 of 1440
Processing band power window 229 of 1440
Processing band power window 230 of 1440
Processing band power window 231 of 1440
Processing band power window 232 of 1440
Processing band power window 233 of 1440
Processing band power window 234 of 1440
Processing band power window 235 of 1440
Processing band power window 236 of 1440
Processing band power window 237 of 1440
Processing band power window 238 of 1440
Processing band power window 239 of 1440
Processing band power window 240 of 1440
Processing band power window 241 of 1440
Processing band power window 242 of 1440
Processing band power window 243 of 1440
Processing band power window 244 of 1440
Processing band power window 245 of 1440
Processing band power window 246 of 1440
Processing band power window 247 of 1440
Processing band power window 248 of 1440
Processing band power window 249 of 1440
Processing band power window 250 of 1440
Processing band power window 251 of 1440
Processing band power window 252 of 1440
Processing band power window 253 of 1440
Processing band power window 254 of 1440
Processing band power window 255 of 1440
Processing band power window 256 of 1440
Processing band power window 257 of 1440
Processing band power window 258 of 1440
Processing band power window 259 of 1440
Processing band power window 260 of 1440
Processing band power window 261 of 1440
Processing band power window 262 of 1440
Processing band power window 263 of 1440
Processing band power window 264 of 1440
Processing band power window 265 of 1440
Processing band power window 266 of 1440
Processing band power window 267 of 1440
Processing band power window 268 of 1440
Processing band power window 269 of 1440
Processing band power window 270 of 1440
Processing band power window 271 of 1440
Processing band power window 272 of 1440
Processing band power window 273 of 1440
Processing band power window 274 of 1440
Processing band power window 275 of 1440
Processing band power window 276 of 1440
Processing band power window 277 of 1440
Processing band power window 278 of 1440
Processing band power window 279 of 1440
Processing band power window 280 of 1440
Processing band power window 281 of 1440
Processing band power window 282 of 1440
Processing band power window 283 of 1440
Processing band power window 284 of 1440
Processing band power window 285 of 1440
Processing band power window 286 of 1440
Processing band power window 287 of 1440
Processing band power window 288 of 1440
Processing band power window 289 of 1440
Processing band power window 290 of 1440
Processing band power window 291 of 1440
Processing band power window 292 of 1440
Processing band power window 293 of 1440
Processing band power window 294 of 1440
Processing band power window 295 of 1440
Processing band power window 296 of 1440
Processing band power window 297 of 1440
Processing band power window 298 of 1440
Processing band power window 299 of 1440
Processing band power window 300 of 1440
Processing band power window 301 of 1440
Processing band power window 302 of 1440
Processing band power window 303 of 1440
Processing band power window 304 of 1440
Processing band power window 305 of 1440
Processing band power window 306 of 1440
Processing band power window 307 of 1440
Processing band power window 308 of 1440
Processing band power window 309 of 1440
Processing band power window 310 of 1440
Processing band power window 311 of 1440
Processing band power window 312 of 1440
Processing band power window 313 of 1440
Processing band power window 314 of 1440
Processing band power window 315 of 1440
Processing band power window 316 of 1440
Processing band power window 317 of 1440
Processing band power window 318 of 1440
Processing band power window 319 of 1440
Processing band power window 320 of 1440
Processing band power window 321 of 1440
Processing band power window 322 of 1440
Processing band power window 323 of 1440
Processing band power window 324 of 1440
Processing band power window 325 of 1440
Processing band power window 326 of 1440
Processing band power window 327 of 1440
Processing band power window 328 of 1440
Processing band power window 329 of 1440
Processing band power window 330 of 1440
Processing band power window 331 of 1440
Processing band power window 332 of 1440
Processing band power window 333 of 1440
Processing band power window 334 of 1440
Processing band power window 335 of 1440
Processing band power window 336 of 1440
Processing band power window 337 of 1440
Processing band power window 338 of 1440
Processing band power window 339 of 1440
Processing band power window 340 of 1440
Processing band power window 341 of 1440
Processing band power window 342 of 1440
Processing band power window 343 of 1440
Processing band power window 344 of 1440
Processing band power window 345 of 1440
Processing band power window 346 of 1440
Processing band power window 347 of 1440
Processing band power window 348 of 1440
Processing band power window 349 of 1440
Processing band power window 350 of 1440
Processing band power window 351 of 1440
Processing band power window 352 of 1440
Processing band power window 353 of 1440
Processing band power window 354 of 1440
Processing band power window 355 of 1440
Processing band power window 356 of 1440
Processing band power window 357 of 1440
Processing band power window 358 of 1440
Processing band power window 359 of 1440
Processing band power window 360 of 1440
Processing band power window 361 of 1440
Processing band power window 362 of 1440
Processing band power window 363 of 1440
Processing band power window 364 of 1440
Processing band power window 365 of 1440
Processing band power window 366 of 1440
Processing band power window 367 of 1440
Processing band power window 368 of 1440
Processing band power window 369 of 1440
Processing band power window 370 of 1440
Processing band power window 371 of 1440
Processing band power window 372 of 1440
Processing band power window 373 of 1440
Processing band power window 374 of 1440
Processing band power window 375 of 1440
Processing band power window 376 of 1440
Processing band power window 377 of 1440
Processing band power window 378 of 1440
Processing band power window 379 of 1440
Processing band power window 380 of 1440
Processing band power window 381 of 1440
Processing band power window 382 of 1440
Processing band power window 383 of 1440
Processing band power window 384 of 1440
Processing band power window 385 of 1440
Processing band power window 386 of 1440
Processing band power window 387 of 1440
Processing band power window 388 of 1440
Processing band power window 389 of 1440
Processing band power window 390 of 1440
Processing band power window 391 of 1440
Processing band power window 392 of 1440
Processing band power window 393 of 1440
Processing band power window 394 of 1440
Processing band power window 395 of 1440
Processing band power window 396 of 1440
Processing band power window 397 of 1440
Processing band power window 398 of 1440
Processing band power window 399 of 1440
Processing band power window 400 of 1440
Processing band power window 401 of 1440
Processing band power window 402 of 1440
Processing band power window 403 of 1440
Processing band power window 404 of 1440
Processing band power window 405 of 1440
Processing band power window 406 of 1440
Processing band power window 407 of 1440
Processing band power window 408 of 1440
Processing band power window 409 of 1440
Processing band power window 410 of 1440
Processing band power window 411 of 1440
Processing band power window 412 of 1440
Processing band power window 413 of 1440
Processing band power window 414 of 1440
Processing band power window 415 of 1440
Processing band power window 416 of 1440
Processing band power window 417 of 1440
Processing band power window 418 of 1440
Processing band power window 419 of 1440
Processing band power window 420 of 1440
Processing band power window 421 of 1440
Processing band power window 422 of 1440
Processing band power window 423 of 1440
Processing band power window 424 of 1440
Processing band power window 425 of 1440
Processing band power window 426 of 1440
Processing band power window 427 of 1440
Processing band power window 428 of 1440
Processing band power window 429 of 1440
Processing band power window 430 of 1440
Processing band power window 431 of 1440
Processing band power window 432 of 1440
Processing band power window 433 of 1440
Processing band power window 434 of 1440
Processing band power window 435 of 1440
Processing band power window 436 of 1440
Processing band power window 437 of 1440
Processing band power window 438 of 1440
Processing band power window 439 of 1440
Processing band power window 440 of 1440
Processing band power window 441 of 1440
Processing band power window 442 of 1440
Processing band power window 443 of 1440
Processing band power window 444 of 1440
Processing band power window 445 of 1440
Processing band power window 446 of 1440
Processing band power window 447 of 1440
Processing band power window 448 of 1440
Processing band power window 449 of 1440
Processing band power window 450 of 1440
Processing band power window 451 of 1440
Processing band power window 452 of 1440
Processing band power window 453 of 1440
Processing band power window 454 of 1440
Processing band power window 455 of 1440
Processing band power window 456 of 1440
Processing band power window 457 of 1440
Processing band power window 458 of 1440
Processing band power window 459 of 1440
Processing band power window 460 of 1440
Processing band power window 461 of 1440
Processing band power window 462 of 1440
Processing band power window 463 of 1440
Processing band power window 464 of 1440
Processing band power window 465 of 1440
Processing band power window 466 of 1440
Processing band power window 467 of 1440
Processing band power window 468 of 1440
Processing band power window 469 of 1440
Processing band power window 470 of 1440
Processing band power window 471 of 1440
Processing band power window 472 of 1440
Processing band power window 473 of 1440
Processing band power window 474 of 1440
Processing band power window 475 of 1440
Processing band power window 476 of 1440
Processing band power window 477 of 1440
Processing band power window 478 of 1440
Processing band power window 479 of 1440
Processing band power window 480 of 1440
Processing band power window 481 of 1440
Processing band power window 482 of 1440
Processing band power window 483 of 1440
Processing band power window 484 of 1440
Processing band power window 485 of 1440
Processing band power window 486 of 1440
Processing band power window 487 of 1440
Processing band power window 488 of 1440
Processing band power window 489 of 1440

,epoch_id,subject_id,session,channel,delta,theta,alpha,beta,gamma,dominant_band
0,0,0,baseline,EEG Fp1,0.495404,0.206765,0.106919,0.149537,0.041375,delta
1,0,0,baseline,EEG Fp2,0.473324,0.217361,0.074882,0.181188,0.053245,delta
2,0,0,baseline,EEG F3,0.505253,0.167638,0.105890,0.185091,0.036128,delta
3,0,0,baseline,EEG F4,0.577215,0.103778,0.044716,0.228933,0.045358,delta
4,0,0,baseline,EEG F7,0.557690,0.162592,0.094005,0.157093,0.028620,delta
...,...,...,...,...,...,...,...,...,...,...
28795,1439,5,task,EEG O2,0.042044,0.100372,0.838641,0.014948,0.003996,alpha
28796,1439,5,task,EEG Fz,0.191824,0.182647,0.379952,0.216824,0.028753,alpha
28797,1439,5,task,EEG Cz,0.178548,0.124164,0.237660,0.424500,0.035127,beta
28798,1439,5,task,EEG Pz,0.240964,0.244673,0.437243,0.060588,0.016531,alpha
28799,1439,5,task,EEG A2-A1,0.624569,0.078462,0.077116,0.180194,0.039659,delta

In [21]:
band_df.to_csv('TDG_band_power_data.csv')